#!/bin/bash
#
# Installation Script for Western Blot Capture API
#
# Installs dependencies, builds C library, and sets up Python environment
# for Raspberry Pi Zero 2W
#
# Usage:
#   cd /home/freddie/sl-wb-pi-api
#   ./scripts/install.sh

set -e  # Exit on any error

echo "============================================"
echo "Western Blot Capture API Installation"
echo "============================================"
echo ""

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "Project directory: $PROJECT_DIR"
echo ""

# Check if running from correct directory
if [ ! -f "$PROJECT_DIR/Makefile" ]; then
    echo "ERROR: Makefile not found in $PROJECT_DIR"
    echo "Please run this script from the project root directory"
    exit 1
fi

# Step 1: Install system dependencies
echo "Step 1: Installing system dependencies..."
echo ""

# Update package list
sudo apt-get update

# Install build essentials
sudo apt-get install -y build-essential gcc make

# Install libxdtusb dependencies
sudo apt-get install -y libcurl4-openssl-dev libusb-1.0-0-dev

# Install Python dependencies
sudo apt-get install -y python3 python3-pip python3-venv

echo "  ✓ System dependencies installed"
echo ""

# Step 2: Install libxdtusb if not present
echo "Step 2: Checking for libxdtusb..."
echo ""

if ldconfig -p | grep -q libxdtusb; then
    echo "  ✓ libxdtusb already installed"
else
    echo "  libxdtusb not found in system"

    # Check if library files exist in libraries
    if [ -f "$PROJECT_DIR/libraries/libxdtusb.so" ]; then
        echo "  Installing libxdtusb from libraries..."
        sudo cp "$PROJECT_DIR/libraries/libxdtusb.so" /usr/local/lib/
        sudo ldconfig
        echo "  ✓ libxdtusb installed"
    else
        echo "  ERROR: libxdtusb.so not found in libraries/"
        echo "  Please place the libxdtusb library files in libraries/"
        exit 1
    fi
fi
echo ""

# Step 3: Build libcapture.so
echo "Step 3: Building libcapture.so..."
echo ""

cd "$PROJECT_DIR"
make clean
make

if [ ! -f "libcapture.so" ]; then
    echo "ERROR: libcapture.so build failed"
    exit 1
fi

echo "  ✓ libcapture.so built successfully"
echo ""

# Step 4: Configure USB device permissions
echo "Step 4: Configuring USB device permissions..."
echo ""

# Detect XDT USB device
echo "  Detecting XDT USB camera..."
XDT_DEVICE=$(lsusb | grep -i "xdt\|slingshot\|detector" | head -n 1)

if [ -z "$XDT_DEVICE" ]; then
    echo "  ⚠ Warning: XDT USB camera not detected"
    echo "  Please connect the camera before starting the service"
    echo "  You can create udev rules manually later if needed"
    echo ""
else
    echo "  Found device: $XDT_DEVICE"

    # Extract vendor and product IDs
    VENDOR_ID=$(echo "$XDT_DEVICE" | grep -oP 'ID \K[0-9a-f]{4}(?=:)')
    PRODUCT_ID=$(echo "$XDT_DEVICE" | grep -oP 'ID [0-9a-f]{4}:\K[0-9a-f]{4}')

    if [ -n "$VENDOR_ID" ] && [ -n "$PRODUCT_ID" ]; then
        echo "  Vendor ID: $VENDOR_ID"
        echo "  Product ID: $PRODUCT_ID"

        # Create udev rule
        UDEV_RULE_FILE="/etc/udev/rules.d/99-xdtusb.rules"
        echo "  Creating udev rule: $UDEV_RULE_FILE"

        sudo tee "$UDEV_RULE_FILE" > /dev/null << EOF
# XDT USB Camera - Allow access for all users
# Generated by Western Blot Capture API installation script
SUBSYSTEM=="usb", ATTRS{idVendor}=="$VENDOR_ID", ATTRS{idProduct}=="$PRODUCT_ID", MODE="0666", GROUP="plugdev"

# Alternative: Match any device from this vendor
# SUBSYSTEM=="usb", ATTRS{idVendor}=="$VENDOR_ID", MODE="0666", GROUP="plugdev"
EOF

        # Reload udev rules
        echo "  Reloading udev rules..."
        sudo udevadm control --reload-rules
        sudo udevadm trigger

        echo "  ✓ USB device permissions configured"
        echo "  Note: You may need to reconnect the camera or reboot for changes to take effect"
    else
        echo "  ⚠ Warning: Could not extract device IDs"
        echo "  You may need to create udev rules manually"
    fi
fi
echo ""

# Step 5: Create Python virtual environment
echo "Step 5: Setting up Python virtual environment..."
echo ""

VENV_DIR="$PROJECT_DIR/venv"

if [ -d "$VENV_DIR" ]; then
    echo "  Virtual environment already exists"
    read -p "  Remove and recreate? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$VENV_DIR"
        python3 -m venv "$VENV_DIR"
        echo "  ✓ Virtual environment recreated"
    else
        echo "  Using existing virtual environment"
    fi
else
    python3 -m venv "$VENV_DIR"
    echo "  ✓ Virtual environment created"
fi
echo ""

# Step 6: Install Python dependencies
echo "Step 6: Installing Python dependencies..."
echo ""

source "$VENV_DIR/bin/activate"

# Upgrade pip
pip install --upgrade pip -q

# Install Flask (minimal dependencies only)
pip install flask

echo "  ✓ Python dependencies installed"
deactivate
echo ""

# Step 7: Install systemd service
echo "Step 7: Installing systemd service..."
echo ""

SERVICE_FILE="$PROJECT_DIR/config/capture.service"

if [ ! -f "$SERVICE_FILE" ]; then
    echo "ERROR: Service file not found: $SERVICE_FILE"
    exit 1
fi

# Copy service file to systemd directory
sudo cp "$SERVICE_FILE" /etc/systemd/system/capture.service

# Reload systemd
sudo systemctl daemon-reload

# Enable service
sudo systemctl enable capture.service

echo "  ✓ Service installed and enabled"
echo ""

# Step 8: Start service
echo "Step 8: Starting service..."
echo ""

sudo systemctl start capture.service
sleep 2

# Check service status
if sudo systemctl is-active --quiet capture.service; then
    echo "  ✓ Service is running!"
else
    echo "  ✗ Service failed to start"
    echo ""
    echo "Viewing last 20 lines of log:"
    sudo journalctl -u capture -n 20 --no-pager
    exit 1
fi
echo ""

# Step 9: Display summary
echo "============================================"
echo "Installation Complete!"
echo "============================================"
echo ""
echo "Service Status:"
sudo systemctl status capture.service --no-pager -l | head -n 10
echo ""
echo "API Endpoints:"
echo "  GET  http://localhost:5000/health"
echo "  POST http://localhost:5000/capture"
echo "  POST http://localhost:5000/shutdown"
echo ""
echo "Useful Commands:"
echo "  • View logs:"
echo "    sudo journalctl -u capture -f"
echo ""
echo "  • Restart service:"
echo "    sudo systemctl restart capture"
echo ""
echo "  • Stop service:"
echo "    sudo systemctl stop capture"
echo ""
echo "  • Check status:"
echo "    sudo systemctl status capture"
echo ""
echo "  • Rebuild library:"
echo "    cd $PROJECT_DIR && make clean && make"
echo ""
echo "  • Test capture:"
echo "    curl -X POST http://localhost:5000/capture -H 'Content-Type: application/json' -d '{\"exposure_ms\": 100}' --output test.raw"
echo ""
